export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_STAGE: 'INVALID_STAGE',
  BUSINESS_RULE_FAILED: 'BUSINESS_RULE_FAILED',
  CSRF_INVALID: 'CSRF_INVALID',
  AI_TIMEOUT: 'AI_TIMEOUT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
